# 是否超频
echo "CONFIG_FIRMWARE_CPU_600MHZ=y" >> .config
echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config
echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config
echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config
echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config
