# 是否超频
echo "CONFIG_FIRMWARE_CPU_600MHZ=y" >> .config
echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y"
echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n"
echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n"
echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n"
